version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: monopoly-empire-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/empire/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - monopoly-network

  backend:
    build:
      context: ./server/empire/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:mysql://db:3306/${DB_DATABASE}?useSSL=false
      - DB_USERNAME
      - DB_PASSWORD
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monopoly-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - monopoly-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/app/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/app/openapi.yaml
    ports:
      - "8081:8080"
    networks:
      - monopoly-network

volumes:
  mysql-data:
    driver: local

networks:
  monopoly-network:
    driver: bridge