version: "3.8"
services:
  backend:
    build:
      context: ./server/monopolyEmpire
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL} # Neon Connection String
    networks:
      - monopoly-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - monopoly-network

networks:
  monopoly-network:
    driver: bridge