version: "3.8"
services:
  backend:
    build:
      context: ./server/empire/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - monopoly-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - monopoly-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/app/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/app/openapi.yaml
    ports:
      - "8081:8080"
    networks:
      - monopoly-network

networks:
  monopoly-network:
    driver: bridge